update prysm version
bnb-chain/greenfield-cometbft pull request #73
Opened 2024-07-01 03:52 UTC by KeefeL

### Description

Update Prysm version

### Rationale

The BSC introduces two different Prsym versions, we want to make it unified

### Example

NA

### Changes

Notable changes:
* NA

2024-07-01 04:01 UTC, unclezoro requested changes
Please fully check the compatibility

2024-07-03 02:16 UTC, KeefeL commented
> Please fully check the compatibility

Done

2024-07-03 02:19 UTC, 1nanosecond approved these changes

2024-07-03 02:55 UTC, unclezoro approved these changes

2024-07-03 02:55 UTC, merged